/oakd:
  ros__parameters:
    camera:
      i_enable_imu: false  # IMU 데이터 사용 (필요시)
      i_enable_ir: false   # IR 프로젝터 사용 (필요시)
      i_floodlight_brightness: 0 # IR 투광기 밝기
      i_laser_dot_brightness: 100 # IR 도트 프로젝터 밝기 
      i_nn_type: none
      i_pipeline_type: RGBD   # 파이프라인: RGB+D (Depth 활성화)
      i_usb_speed: SUPER_PLUS
    rgb:
      i_board_socket_id: 0
      i_fps: 30.0
      i_height: 480
      i_interleaved: false
      i_max_q_size: 10
      i_preview_size: 250
      i_enable_preview: true
      i_low_bandwidth: true
      i_keep_preview_aspect_ratio: true
      i_publish_topic: true   #전체 해상도 영상 비활성 (프리뷰만 퍼블리시)
      i_resolution: '1080P'
      i_width: 640
    stereo:
      i_publish_topic: true
      i_align_depth: true
    use_sim_time: false
